# Generated by Django 5.2 on 2025-04-05 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('release_year', models.IntegerField()),
                ('content_type', models.CharField(choices=[('movie', 'Película'), ('series', 'Serie'), ('documentary', 'Documental')], max_length=20)),
                ('thumbnail', models.URLField()),
                ('video_file', models.URLField()),
                ('min_subscription_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.subscriptionplan')),
                ('genres', models.ManyToManyField(to='content.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('episode_number', models.IntegerField()),
                ('season_number', models.IntegerField()),
                ('video_file', models.URLField()),
                ('duration', models.IntegerField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='content.content')),
            ],
        ),
    ]
